add gallery section / WDP230401-27
odevpl/wdp-2304 pull request #32
Opened 2023-04-19 14:00 UTC by Wasil-pl

2023-04-19 16:05 UTC, MaciejMl commented
Darek jak byś mógł się pozbyć najpierw konfliktów to bym spojrzał na kod

2023-04-19 16:27 UTC, Wasil-pl commented
gotowe

2023-04-19 16:50 UTC, MaciejMl commented
Jeszcze coś w NewFurniture sie pokazało ;-)

2023-04-19 16:52 UTC, MaciejMl commented
Najprawdopodobniej to wynik tego że ja przed chwilą pozbywałem się konfliktów w swoim PR a też dotyczył NewFurniture, więc nie zapomnij najpierw zrobić pull z matera

2023-04-19 16:53 UTC, Wasil-pl commented
spoko, właśnie VLC mi komunikuje na czerwono że jestem dwa commity do tyłu :)

2023-04-19 18:13 UTC, MaciejMl requested changes
Nie mogę wejść na brancha więc nie mogę sprawdzić (póki co, może w międzyczasie Patryk wytłumaczy jak to zrobić) ale wygląda wszystko ok oprócz jednej uwagi, którą mógłbyś sprawdzić.

2023-04-19 18:31 UTC, Wasil-pl commented on src/components/features/NewFurniture/NewFurniture.js
> -                    <div className={`${fade ? styles.fadeOut : styles.fadeIn}`}>
Sorry, chyba przy którymś conflictcie musiałem przez przypadek wybrac nie tą opcję. Przejrzę wcześniejsze commit i poprawię :)

2023-04-19 18:51 UTC, MaciejMl commented
Mam też oddzielne pytanko jaka jest nazwa tego brancha WDP230401-27? czy może jakoś inaczej? tak sprawdzam dlaczego nie mogę na niego wejść żeby sprawdzić jak działa

2023-04-20 15:45 UTC, MaciejMl approved these changes

2023-04-20 15:47 UTC, merged